### ISSUE TITLE
I cannot update Latitude after selecting latest version

### ISSUE THREAD

**Issue by abgonzalez93** [latitude-dev/latitude#453] opened 2024-05-27 10:01 UTC
### Environment

- Node version (`node -v`): 20.12.2
- npm version (`npm -v`): 10.8.0
- Latitude CLI version (`latitude --version`): 1.6.6
- Latitude project version (check `latitude.json` at the root of your project): 1.2.3
- OS: Ubuntu 22.04.3

## Actual Behaviour

After updating to the latest version of Latitude (`latitude dev`), I encountered this error. I've also attempted to install earlier versions...

![imagen](https://github.com/latitude-dev/latitude/assets/39385878/d52e110a-d3ec-4f12-b698-0bbd0ecd57ec)
[latitude_log_err.txt](https://github.com/latitude-dev/latitude/files/15454285/latitude_log_err.txt)

**Comment by csansoon** [comment] 2024-05-27 10:07
Hello @abgonzalez93! Try updating the CLI by running `npm update -g @latitude-data/cli`

**Comment by abgonzalez93** [comment] 2024-05-27 10:13
I also used `npm update -g @latitude-data/cli`, sorry for not mentioning it, but it also didn't work

**Comment by andresgutgon** [comment] 2024-05-27 10:19
Hi @abgonzalez93 are you using a VPN to connect to the internet? The error suggests is failing to fetch the info from our telemetry server provider 

`Error getaddrinfo EAI_AGAIN ...`

**Comment by abgonzalez93** [comment] 2024-05-27 10:30
I'm not using VPN.
I disabled the telemetry option on Latitude.
It's working on DEV, but I can't update the app anymore.

**Comment by andresgutgon** [comment] 2024-05-27 10:38
Ok can you run `dev` with `--debug` and `--verbose`

```bash
latitude dev --debug --verbose
```
Do you see logs when you change a query or a view and save the file?

**Comment by abgonzalez93** [comment] 2024-05-27 10:45
Done.
I do see logs when I do those changes.

![imagen](https://github.com/latitude-dev/latitude/assets/39385878/733a3184-4f4c-4b50-b6eb-c23a8867d6ac)

**Comment by andresgutgon** [comment] 2024-05-27 10:49
I see, the CLI detects the change but the UI is not updated, right? I see a query error in the screenshot. Can you fix it and see if the UI updates?

**Comment by abgonzalez93** [comment] 2024-05-27 10:54
Oh yeah, the UI updates once I fix the error in the code. Everything is OK

**Comment by andresgutgon** [comment] 2024-05-27 11:47
Awesome. Regarding your initial issue, I don't know what can be the cause. I'll leave it open for now

**Comment by geclos** [comment] 2024-05-27 15:20
@andresgutgon regardless of what's causing this error, the CLI should fail gracefully and continue working, we don't want CLI commands to depend on rudderstack's servers. This should be a quick fix no/

**Comment by andresgutgon** [comment] 2024-05-27 15:23
I think so. Try/catch it but I'm confused because I tried and it didn't fail in my case so maybe it is something related to timing (Rudder stack was down when Antonio tried) or with something different in Ubuntu. 

Anyway I'll try / catch telemetry call

**Comment by andresgutgon** [comment] 2024-06-03 08:19
That PR should fix this problem. Closing this issue. Let us know if you see it again @abgonzalez93

**Closed by andresgutgon** 2024-06-03 08:19 UTC
Labels: bug
